kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-db
  namespace: applicationnamespace
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi