kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-db-pvc
  namespace: applicationnamespace
spec:
  storageClassName: gcp-storage-class
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi