kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gcp-storage-class
  namespace: applicationnamespace
provisioner: kubernetes.io/gce-pd
# parameters:
#   storageaccounttype: Standard_LRS
#   kind: Managed
#   type: azure-disk

