apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqldb-pvc
  namespace: applicationnamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard