kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: azure-disk-db
  namespace: applicationnamespace
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
  type: azure-disk-db
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-db
  namespace: applicationnamespace
  annotations:
    volume.beta.kubernetes.io/storage-class: azure-disk
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi